### ISSUE TITLE
Improve "Setting Up Metanorma"

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma.com#132]
This is urgent, because of the failures of onboarding new editors we have had.

https://www.metanorma.com/author/topics/install needs to be updated.

* rvm or rbenv needs to be discussed and injected as installation step; without that, people are unable to do any bundle install of gems (as Timofey has just discovered on Ubuntu).
  * I am not going to do it myself, because I have no idea how rvm interacts with docker, and I don't understand this stuff anyway.

Any other confusion that emerges from onboarding the new editors should go here as well.

**Comment by opoudjis** [comment]
I'm assigning this task to all four of you; someone who understands docker and Windows Metanorma needs to update the Install page. @strogonoff, please coordinate.

**Comment by ronaldtse** [comment]
Ruby version managers like RVM and rbenv are NOT necessary. 

And the docker setup is separate.  You do not need a ruby version manager if you use docker. 

The Ruby version manager is only necessary if your system Ruby is of a version we no longer support, like 2.3.

**Comment by ronaldtse** [comment]
Moreover, the windows and Mac setup of docker are also different. 

For Windows, we strongly recommend using the chocolatey package. And for macOS, use Homebrew. Soon for Linux, we will use snap.

**Comment by opoudjis** [comment]
> The Ruby version manager is only necessary if your system Ruby is of a version we no longer support, like 2.3.

Which includes mine and yours, and as he found, Tim's. (For a distinct reason: no write permissions to the system Ruby installation.) So it has to be documented.

**Comment by ronaldtse** [comment]
We now have a better alternative with packed-mn for non-customized MN, but will need extensive testing to verify it works all the time. For developmental work that our editors currently use, the development workflow will be necessary.

**Comment by anermina** [comment]
The problem I've had is described below.

After successful Metanorma installation using Chocolatey on Windows 10 OS, make command (make -f Makefile.win SHELL=cmd) was unsuccessful. However, .html and .doc files (without figures) could be generated using the following command:
metanorma --type itu fileName.adoc

AsciiDoc files with figures couldn't have been generated using any of the above given commands. 

Make command (faulty) output:
A subdirectory or file C:\Users\Nermina\.cache\xml2rfc already exists.
'yq' is not recognized as an internal or external command,
operable program or batch file.

Metanorma ITU command (faulty) output:
...ErkJggg== (Errno::ENOENT)

Problem was solved by manually installing yq.exe and adding it to PATH in system variables. Make command (make -f Makefile.win SHELL=cmd) is successful now. @CAMOBAP795, thank you!

Making files using command in the format [metanorma --type itu fileName.adoc] is still unsuccessful, but since there is the other way for generating .doc and .html files, it is not a problem for me any longer.

**Comment by CAMOBAP795** [comment]
@anermina regarding the problem with `` can you confirm that you have the same problem as me below?

```
mn-samples-itu(master ✔) metanorma --type itu sources/G.650.1-201803.adoc
[relaton] Info: detecting backends:
[relaton] processor "relaton_iec" registered
[relaton] processor "relaton_iso" registered
[relaton] processor "relaton_ietf" registered
[relaton] processor "relaton_gb" registered
[relaton] processor "relaton_nist" registered
[relaton] processor "relaton_itu" registered
Traceback (most recent call last):
	34: from /usr/local/bin/metanorma:23:in `<main>'
	33: from /usr/local/bin/metanorma:23:in `load'
	32: from /Library/Ruby/Gems/2.6.0/gems/metanorma-cli-1.2.9/exe/metanorma:20:in `<top (required)>'
	31: from /Library/Ruby/Gems/2.6.0/gems/metanorma-cli-1.2.9/lib/metanorma/cli.rb:60:in `start'
	30: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	29: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	28: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	27: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	26: from /Library/Ruby/Gems/2.6.0/gems/metanorma-cli-1.2.9/lib/metanorma/cli/command.rb:34:in `compile'
	25: from /Library/Ruby/Gems/2.6.0/gems/metanorma-cli-1.2.9/lib/metanorma/cli/compiler.rb:33:in `compile'
	24: from /Library/Ruby/Gems/2.6.0/gems/metanorma-cli-1.2.9/lib/metanorma/cli/compiler.rb:29:in `compile'
	23: from /Library/Ruby/Gems/2.6.0/gems/metanorma-cli-1.2.9/lib/metanorma/cli/compiler.rb:41:in `compile_file'
	22: from /Library/Ruby/Gems/2.6.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:17:in `compile'
	21: from /Library/Ruby/Gems/2.6.0/gems/metanorma-0.3.14/lib/metanorma/compile.rb:101:in `process_input'
	20: from /Library/Ruby/Gems/2.6.0/gems/metanorma-itu-1.0.6/lib/metanorma/itu/processor.rb:26:in `input_to_isodoc'
	19: from /Library/Ruby/Gems/2.6.0/gems/metanorma-0.3.14/lib/metanorma/input/asciidoc.rb:8:in `process'
	18: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
	17: from /Library/Ruby/Gems/2.6.0/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
	16: from /Library/Ruby/Gems/2.6.0/gems/metanorma-standoc-1.3.0/lib/asciidoctor/standoc/utils.rb:137:in `convert'
	15: from /Library/Ruby/Gems/2.6.0/gems/metanorma-itu-1.0.6/lib/asciidoctor/itu/converter.rb:80:in `document'
	14: from /Library/Ruby/Gems/2.6.0/gems/metanorma-itu-1.0.6/lib/asciidoctor/itu/converter.rb:35:in `makexml'
	13: from /Library/Ruby/Gems/2.6.0/gems/metanorma-standoc-1.3.0/lib/asciidoctor/standoc/utils.rb:157:in `noko'
	12: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:254:in `with'
	11: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:254:in `new'
	10: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:295:in `initialize'
	 9: from /Library/Ruby/Gems/2.6.0/gems/metanorma-itu-1.0.6/lib/asciidoctor/itu/converter.rb:35:in `block in makexml'
	 8: from /Library/Ruby/Gems/2.6.0/gems/metanorma-standoc-1.3.0/lib/asciidoctor/standoc/base.rb:179:in `front'
	 7: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	 6: from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/builder.rb:394:in `insert'
	 5: from /Library/Ruby/Gems/2.6.0/gems/metanorma-standoc-1.3.0/lib/asciidoctor/standoc/base.rb:180:in `block in front'
	 4: from /Library/Ruby/Gems/2.6.0/gems/metanorma-standoc-1.3.0/lib/asciidoctor/standoc/front.rb:218:in `metadata'
	 3: from /Library/Ruby/Gems/2.6.0/gems/metanorma-standoc-1.3.0/lib/asciidoctor/standoc/front.rb:263:in `title'
	 2: from /Library/Ruby/Gems/2.6.0/gems/metanorma-itu-1.0.6/lib/asciidoctor/itu/front.rb:20:in `title_english'
	 1: from /Library/Ruby/Gems/2.6.0/gems/metanorma-itu-1.0.6/lib/asciidoctor/itu/front.rb:20:in `each'
/Library/Ruby/Gems/2.6.0/gems/metanorma-itu-1.0.6/lib/asciidoctor/itu/front.rb:23:in `block in title_english': undefined method `asciidoc_sub' for Asciidoctor::Standoc::Utils:Module (NoMethodError)
```

version:

```
metanorma version                               
Metanorma 0.3.14
Metanorma::Cli 1.2.9
[relaton] processor "relaton_gb" registered
Metanorma::Standoc 1.3.0/IsoDoc 1.0.0
Metanorma::ISO 1.3.0
Metanorma::Iec 0.1.6
Metanorma::Ietf 2.0.2
Metanorma::Gb 1.3.0
Metanorma::Csd 1.3.0
Metanorma::Csa 1.4.2
Metanorma::M3d 1.3.0
Metanorma::Acme 1.4.0
Metanorma::Unece 0.2.0
Metanorma::NIST 0.2.0
Metanorma::Ogc 0.2.0
Metanorma::ITU 1.0.6
```

**Comment by anermina** [comment]
@CAMOBAP795 Unfortunately, I don't have a full output, but these were the last lines:
TRjysnJT7eRQmjKSnPKMpYg5L7bN68handTH3mbUxB5z65P263YlJincc/JVcVR+0Nt+Ykj4/Pc7hdrIeb1s3mN/+dUPJS/P0+YVr3ZQkjM1uxPuctCcXmaIymnMRLEr53fM14LFcm9ydfTTqxnJQkSepzlpOSVD2Wk5Io8Ujrbt1jjXKU0neX4kiSJEnqMhYg/8+k+dV+SVJvsTbbKQkbckgaTExxZ0o6LyS3m+48FhgxekWyenG0ACM+GRm6sCxs2nmX/c3f/H/x+FGdFizktwAAAABJRU5ErkJggg== (Errno::ENOENT)

While this problem was present, I was using following versions:
PS D:\Upwork\mn-samples-itu-master> metanorma -v
Metanorma 0.3.15
Metanorma::Cli 1.2.7
LaTeXML not found in PATH, please ensure that LaTeXML is installed.
Metanorma::Standoc 1.3.2/IsoDoc 1.0.2
Metanorma::ISO 1.3.3
Metanorma::Iec 0.0.5
Metanorma::Ietf 1.0.6
Metanorma::Gb 1.3.3
Metanorma::Csd 1.3.2
Metanorma::Csand 1.3.2
Metanorma::Csand 1.3.2
Metanorma::M3d 1.3.2
Metanorma::Acme 1.3.2
Metanorma::Unece 0.2.3
Metanorma::NIST 0.2.3
Metanorma::Ogc 0.2.3
Metanorma::ITU 0.2.4

The good thing is that the problem was solved in the meanwhile... With some bundle update, I think.

Currently, I'm using following versions:
PS D:\Upwork\mn-samples-itu> metanorma -v
Metanorma 0.3.18
Metanorma::Cli 1.2.9
Metanorma::Standoc 1.3.17/IsoDoc 1.0.16
Metanorma::ISO 1.3.16
Metanorma::Iec 0.1.7
Metanorma::Ietf 2.0.3
Metanorma::Gb 1.3.15
Metanorma::Csd 1.3.12
Metanorma::Csa 1.4.3
Metanorma::M3d 1.3.12
Metanorma::Acme 1.4.0
Metanorma::Unece 0.2.14
Metanorma::NIST 0.2.14
Metanorma::Ogc 0.2.13
Metanorma::ITU 1.0.7
Metanorma::Rsd 1.3.7
Metanorma::Mpfd 0.3.7

**Comment by CAMOBAP795** [comment]
Thanks, @anermina for update

**Comment by CAMOBAP** [comment]
@anermina I'm kind of lost track on this, is anything still need to be done in the scope of this task?

**Comment by anermina** [comment]
@CAMOBAP For me, it's all good now and if no one else has any issue to add, I believe this ticket can be closed.
