### ISSUE TITLE
Difficulty in copying from code

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma.com#77]
The TIP section today makes it hard to copy sample code to paste:

(https://www.metanorma.com/software/metanorma-iso/docs/guidance/#references-to-standards)

<img width="775" alt="image" src="https://user-images.githubusercontent.com/11865/55546276-876a8680-5701-11e9-9bc5-1e4d69b482a7.png">

When I highlight the bottom line, it often highlights the rest and causes the page to shift. A user would expect to be easily able to copy and paste sample code.

**Comment by strogonoff** [comment]
@ronaldtse 

Couldn’t reproduce. Maybe I don’t understand the issue—can you post a video and report specific browser/OS versions?

When reproducing I found that selection works as usual, either with a triple-click or by dragging the selection. Page doesn’t shift in any browser. Worked in FF, Chrome, Safari on macOS.

Demo (first triple-click, second dragging, Firefox):

![Issue77](https://user-images.githubusercontent.com/292959/55597804-f982b000-5781-11e9-9c3f-52065fee3942.gif)

On triple-click under Safari, “double selection” appears making it seem like the whole tip block is selected, while in fact only the code line will be copied. I have no idea why it happens, my theory it’s because jekyll-asciidoctor generates tables (!!!) for admonition blocks, and this is simply how Safari’s triple-click selection works with tables (with secondary selection spanning the affected table cell).

I did spot one problem thanks to your screenshot—admonition block contents shouldn’t scroll horizontally, only code blocks should. I’ll file separately against Open Project theme.

**Comment by strogonoff** [comment]
I’ll mark as “invalid” (for the lack of “can’t reproduce”), will remove if the bug confirms.

**Comment by ronaldtse** [comment]
![ScreenRecording20190405at2](https://user-images.githubusercontent.com/11865/55608404-ef2bda80-57b0-11e9-9522-2127fd7fb027.gif)

Echoing the above:
1. Code must wrap.
2. A TIP should not be a table.
3. Please make it easy to copy. Not many people like triple-clicks.

**Comment by strogonoff** [comment]
@ronaldtse 

> A TIP should not be a table.

100% behind this. https://github.com/asciidoctor/jekyll-asciidoc/issues/211

**Comment by strogonoff** [comment]
@ronaldtse 

> Please make it easy to copy.

To make copying easier I’ll add a “Copy” button per this issue.

> Code must wrap.

I’ll research a widget that does what you request, but under a separate issue. 

> Not many people like triple-clicks.

I only mentioned triple-click in case you used triple-click. You did not specify how you were selecting.

**Comment by ronaldtse** [comment]
> To make copying easier I’ll add a “Copy” button per this issue.

This works too!

**Comment by strogonoff** [comment]
Copy button feature going in the next relase 2.0.15, next couple days Metanorma.com will be updated.

**Comment by ronaldtse** [comment]
Thanks @strogonoff !

**Comment by strogonoff** [comment]
(Changes are live
